apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: gogs-openshift-docker
  name: gogs-openshift-docker
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: gogs-openshift-docker:latest
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/dshirley-redhat/gogs-openshift-docker.git
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: vOhbLn_drIFMBNYBs9CX
    type: GitHub
  - generic:
      secret: 9O79BE0liHcdVHsmK9v0
    type: Generic
  - type: ConfigChange
