kind: ConfigMap
apiVersion: v1
metadata:
  name: gogs-config
  labels:
    app: gogs
data:
  app.ini: |
    RUN_MODE = prod
    RUN_USER = gogs

    GOGS_LOG__LEVEL = Debug

    [database]
    DB_TYPE  = postgres
    HOST     = postgresql:5432
    NAME     = gogsdb
    USER     = user2WH
    PASSWD   = SXjGNJvQ62NSAi3d

    [repository]
    ROOT = /opt/gogs/data/repositories

    [server]
    ROOT_URL=http://gogs.apps.dshirley1ipi.vmware.tamlab.rdu2.redhat.com
    SSH_DOMAIN=gogs.apps.dshirley1ipi.vmware.tamlab.rdu2.redhat.com

    [security]
    INSTALL_LOCK = true

    [service]
    ENABLE_CAPTCHA = false

    [webhook]
    SKIP_TLS_VERIFY = true
